import type { Creator, Invoice } from '@/types'

// Builds the printable HTML for an invoice — fed to expo-print (see
// lib/invoicePdf.ts). Kept as plain inline-styled HTML (no external
// stylesheet/fonts) since expo-print renders this in an isolated context.

function formatINR(amount: number): string {
  return `₹${amount.toLocaleString('en-IN')}`
}

function formatDate(dateStr: string): string {
  const [year, month, day] = dateStr.split('-').map(Number)
  return new Date(year, month - 1, day).toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })
}

export function buildInvoiceHtml(invoice: Invoice, creator: Creator): string {
  const paymentLines = [
    creator.upi_id ? `UPI ID: ${creator.upi_id}` : null,
    creator.bank_account_number ? `Account: ${creator.bank_account_number}` : null,
    creator.ifsc_code ? `IFSC: ${creator.ifsc_code}` : null,
  ]
    .filter(Boolean)
    .join('<br/>')

  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1C1815; padding: 32px; }
  .header { display: flex; justify-content: space-between; margin-bottom: 28px; }
  .from strong { display: block; font-size: 16px; margin-bottom: 4px; }
  .from { font-size: 12px; color: #6B6259; line-height: 1.7; }
  .num { text-align: right; }
  .num .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em; color: #9A9186; }
  .num .value { font-size: 20px; font-weight: 700; }
  .num .date { font-size: 12px; color: #6B6259; margin-top: 2px; }
  .bill-to { background: #F6F2EC; border-radius: 8px; padding: 14px; margin-bottom: 20px; }
  .bill-to .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em; color: #9A9186; margin-bottom: 4px; }
  .bill-to .name { font-size: 15px; font-weight: 600; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: #9A9186; padding: 8px 0; border-bottom: 1px solid #E5DFD5; }
  td { padding: 12px 0; font-size: 13px; border-bottom: 1px solid #E5DFD5; }
  td:last-child, th:last-child { text-align: right; }
  .totals { margin-top: 8px; }
  .totals .row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 13px; color: #6B6259; }
  .totals .final { font-size: 16px; font-weight: 700; color: #1C1815; border-top: 1px solid #E5DFD5; padding-top: 10px; margin-top: 4px; }
  .payment-details { margin-top: 24px; padding-top: 16px; border-top: 1px solid #E5DFD5; font-size: 11px; color: #6B6259; line-height: 1.8; }
  .watermark { text-align: right; margin-top: 16px; font-size: 10px; color: #9A9186; }
</style>
</head>
<body>
  <div class="header">
    <div class="from">
      <strong>${creator.name}</strong>
      Content Creator${creator.phone ? `<br/>${creator.phone}` : ''}
      ${creator.gstin ? `<br/>GSTIN: ${creator.gstin}` : ''}
    </div>
    <div class="num">
      <div class="label">Invoice</div>
      <div class="value">${invoice.invoice_number}</div>
      <div class="date">${formatDate(invoice.invoice_date)}</div>
    </div>
  </div>

  <div class="bill-to">
    <div class="label">Bill to</div>
    <div class="name">${invoice.brand_name}</div>
    ${
      invoice.brand_contact_person || invoice.brand_contact_email
        ? `<div style="font-size:12px;color:#6B6259;margin-top:2px;">${[invoice.brand_contact_person, invoice.brand_contact_email].filter(Boolean).join(' · ')}</div>`
        : ''
    }
  </div>

  <table>
    <thead><tr><th>Description</th><th>Amount</th></tr></thead>
    <tbody>
      <tr><td>${invoice.description}</td><td>${formatINR(invoice.amount)}</td></tr>
    </tbody>
  </table>

  <div class="totals">
    <div class="row"><span>Subtotal</span><span>${formatINR(invoice.amount)}</span></div>
    ${
      invoice.gst_applicable
        ? `<div class="row"><span>GST (${invoice.gst_rate}%)</span><span>${formatINR(invoice.gst_amount)}</span></div>`
        : ''
    }
    ${
      invoice.tds_deducted && invoice.tds_amount
        ? `<div class="row"><span>TDS deducted</span><span>-${formatINR(invoice.tds_amount)}</span></div>`
        : ''
    }
    <div class="row final">
      <span>Total due</span>
      <span>${formatINR(invoice.total_amount - (invoice.tds_deducted ? invoice.tds_amount ?? 0 : 0))}</span>
    </div>
  </div>

  ${
    paymentLines || invoice.payment_due_date
      ? `<div class="payment-details">
          <strong style="color:#1C1815;display:block;margin-bottom:4px;">Payment details</strong>
          ${paymentLines}
          ${invoice.payment_due_date ? `<br/>Payment due: ${formatDate(invoice.payment_due_date)}` : ''}
        </div>`
      : ''
  }

  <div class="watermark">Generated by CreatorDesk</div>
</body>
</html>
  `.trim()
}
