import qrcode from 'qrcode-generator'
import Svg, { Path, Rect } from 'react-native-svg'

export interface QrCodeProps {
  /** What the code encodes. For TOTP this is the otpauth:// URI. */
  value: string
  size?: number
  /** Dark modules. Defaults to black, which is what scanners expect. */
  color?: string
  background?: string
}

/**
 * A QR code, drawn rather than fetched.
 *
 * `lib/upi.ts` already builds one for the invoice PDF, but it returns an SVG
 * tag as a string, which is right for HTML handed to a PDF renderer and no use
 * at all inside React Native. This draws the same matrix with react-native-svg
 * so it works on a phone, in Expo Go and on the web from one component.
 *
 * Nothing is fetched. A QR code for a two-factor secret must never be
 * generated by a server: the whole point of the secret is that it exists in
 * two places, the authenticator app and Supabase, and putting it through an
 * image service would make that three.
 *
 * One `<Path>` rather than a rect per module. A version-2 code is 25x25, so
 * the naive version mounts several hundred views and drops frames on an older
 * Android phone for no visual difference.
 */
export function QrCode({ value, size = 200, color = '#000000', background = '#FFFFFF' }: QrCodeProps) {
  // Type 0 lets the library pick the smallest version that fits. 'M' recovery
  // survives a slightly dirty screen without inflating the module count.
  const qr = qrcode(0, 'M')
  qr.addData(value)
  qr.make()

  const count = qr.getModuleCount()
  // A quiet zone is part of the spec, not decoration: without it many scanners
  // simply never lock on.
  const quiet = 2
  const total = count + quiet * 2
  const cell = size / total

  let path = ''
  for (let row = 0; row < count; row++) {
    for (let col = 0; col < count; col++) {
      if (!qr.isDark(row, col)) continue
      const x = (col + quiet) * cell
      const y = (row + quiet) * cell
      path += `M${x} ${y}h${cell}v${cell}h-${cell}z`
    }
  }

  return (
    <Svg width={size} height={size}>
      <Rect x={0} y={0} width={size} height={size} fill={background} />
      <Path d={path} fill={color} />
    </Svg>
  )
}
